### ISSUE TITLE
webp 图片破损

### ISSUE THREAD

**Issue by ilharp** [koishijs/handbook#3]
@MirrorCY

默认禁止了 png 和 ico 以外的图片上传。

https://github.com/koishijs/handbook/blob/82ffe0010e04221b07cd6b599690c9e642af5c16/.gitattributes#L1-L4

解决方法：

1. 将本地 webp 图片备份后删除，提交

2. `.gitattributes` 添加如下的一行：

```diff
  * text eol=lf
  
  *.png -text
  *.ico -text
+ *.webp -text
```

3. 再次添加 webp，与该修改的文件一并提交。

**Comment by MirrorCY** [comment]
Fixed by #4
